# Keyword dictionary configuration file
# Contains keywords of different categories and their score weights (keep keywords as short as possible, max 2 words)

categories:
  confidence:
    score_delta: 2
    keywords:
      - "sure"
      - "definitely"
      - "certain"
      - "absolutely"
      - "confident"
      - "guaranteed"
      - "affirmative"
      - "yes"
      - "clear"
      - "right"
      - "correct"
      - "true"
      - "indeed"
      - "exactly"
      - "confirmed"
      - "assured"
      - "undoubtedly"
      - "settled"
      - "decided"
      - "resolved"
      - "certainly"
      - "obviously"
      - "evident"
      - "assure"
      - "done"
      - "fixed"
      - "solved"
      - "ok"
      - "fine"
      - "perfect"
      - "great"
      - "excellent"
      - "awesome"
      - "works"
      - "easy"
      - "simple"
      - "smooth"
      - "stable"
      - "success"
      - "ready"
      - "received"
      - "noted"
      - "proceed"
      - "on it"
      - "handled"
      - "all set"
      - "all good"
      - "no doubt"
      - "no problem"
      - "no issue"
      - "right away"
      - "count on"
      - "can do"
      - "move on"
      - "move up"
      - "go ahead"
      - "let's go"
      - "let's do"
      - "let's start"
      - "let's begin"

  hesitation:
    score_delta: -2
    keywords:
      - "maybe"
      - "perhaps"
      - "not sure"
      - "not certain"
      - "think"
      - "believe"
      - "suppose"
      - "guess"
      - "possibly"
      - "uncertain"
      - "unsure"
      - "not clear"
      - "not positive"
      - "not convinced"
      - "not confident"
      - "not exactly"
      - "not really"
      - "not quite"
      - "not definite"
      - "not obvious"
      - "not evident"
      - "not settled"
      - "not decided"
      - "not resolved"
      - "not ready"
      - "I think"
      - "I feel"
      - "I wonder"
      - "I hope"
      - "I wish"
      - "I doubt"
      - "I question"
      - "I hesitate"
      - "I worry"
      - "I fear"
      - "I suspect"
      - "I assume"
      - "I imagine"
      - "I might"
      - "I could"
      - "I may"
      - "don't know"

  escalation:
    score_delta: -3
    keywords:
      - "urgent"
      - "emergency"
      - "critical"
      - "asap"
      - "immediately"
      - "now"
      - "instantly"
      - "important"
      - "priority"
      - "must"
      - "need"
      - "needs"
      - "required"
      - "fix now"
      - "fix asap"
      - "fix it"
      - "must fix"
      - "must act"
      - "must do"
      - "must handle"
      - "must address"
      - "must respond"
      - "must repair"
      - "must solve"
      - "must correct"
      - "must finish"
      - "must send"
      - "must update"
      - "must check"
      - "must review"
      - "must approve"
      - "must inform"
      - "must notify"
      - "must alert"
      - "must warn"
      - "must report"
      - "must call"
      - "must reply"
      - "must help"
      - "must assist"
      - "must act"
      - "act now"
      - "act fast"
      - "act quick"

  repair:
    score_delta: 1
    keywords:
      - "sorry"
      - "apologize"
      - "apologies"
      - "regret"
      - "oops"
      - "forgive"
      - "excuse"
      - "pardon"
      - "fix"
      - "correct"
      - "improve"
      - "change"
      - "update"
      - "resolve"
      - "repair"
      - "handle"
      - "address"
      - "try"
      - "avoid"
      - "prevent"
      - "ensure"
      - "check"
      - "review"
      - "clarify"
      - "explain"
      - "support"
      - "help"
      - "assist"
      - "cooperate"
      - "coordinate"
      - "inform"
      - "notify"
      - "report"
      - "respond"
      - "reply"
      - "answer"
      - "listen"
      - "careful"
      - "cautious"
      - "mindful"
      - "aware"
      - "responsible"
      - "accountable"
      - "reliable"
      - "trustworthy"
      - "honest"
      - "transparent"
      - "open"
      - "sincere"
      - "genuine"
      - "kind"
      - "polite"
      - "respectful"
      - "patient"
      - "understand"
      - "supportive"
      - "helpful"
      - "flexible"
      - "adaptable"
      - "proactive"
      - "positive"
      - "optimistic"
      - "encourage"
      - "motivate"
      - "inspire"
      - "empower"
      - "uplift"
      - "appreciate"
      - "grateful"
      - "thankful"
      - "generous"
      - "forgiving"
      - "compassion"
      - "empathy"
      - "considerate"
      - "attentive"
      - "diligent"
      - "dedicated"
      - "committed"
      - "dependable"
      - "loyal"
      - "faithful"
      - "devoted"

# Special pattern configuration
not_patterns:
  # When matching "not + adjective", handle as follows:
  # If the adjective is in the confidence category, its negated form should be classified as hesitation
  confidence_to_hesitation:
    - "not sure"
    - "not certain" 
    - "not clear"
    - "not positive"
    - "not convinced"
    - "not confident"
    - "not exactly"
    - "not really"
    - "not quite"
    - "not definite"
    - "not obvious"
    - "not evident"
    - "not settled"
    - "not decided"
    - "not resolved"
    - "not ready"
  # Generic not pattern: match "not + any word"
  generic_not_pattern: true

# Default configuration
default_score: 0
case_sensitive: false
